[package]
name = "aoc_2015_03"
version = "1.0.0"
authors.workspace = true
license = "mit"
edition = "2021"

[lib]
name = "aoc_2015_03"
path = "./src/lib.rs"

[dependencies]
aoclib = { path = "../../lib" }

[dev-dependencies]
criterion = "*"

[[bench]]
name = "bench"
harness = false
