[workspace]

members = [
    "solutions/rust/lib",
    "solutions/rust/2015/*",
]

[workspace.package]
authors = ["Pratyush Choudhary <pratyush3757@gmail.com>"]
license = "mit"
edition = "2021"

[profile.bench]
lto = true

[profile.release]
overflow-checks = true

[profile.dev]
opt-level = 3
