[package]
name = "aoc_2015_11"
version = "1.0.0"
authors.workspace = true
license = "mit"
edition = "2021"

[lib]
name = "aoc_2015_11"
path = "./src/lib.rs"

[dependencies]
aoclib = { path = "../../lib" }

[dev-dependencies]
test-case.workspace = true
