[package]
name = "aoc_2015_04"
version = "1.0.0"
authors.workspace = true
license = "mit"
edition = "2021"

[lib]
name = "aoc_2015_04"
path = "./src/lib.rs"

[dependencies]
aoclib = { path = "../../lib" }
md5 = "0.7.0"

[dev-dependencies]
test-case.workspace = true
