[package]
name = "aoc_2015_08"
version = "1.0.0"
authors.workspace = true
license = "mit"
edition = "2021"

[lib]
name = "aoc_2015_08"
path = "./src/lib.rs"

[dependencies]
aoclib = { path = "../../lib" }
fancy-regex = "0.10.0"
lazy_static = "1.4.0"
